config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  #
  # get 'sessions/create'
  #
  # get 'sessions/destroy'
  #
  # get 'users/new'
  #
  # get 'welcome/index'
  #
  # get 'welcome/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get('/', {to: 'welcome#index', as: 'home'})

  resources :stuff

  # get '/new_path/' => 'ideas#newhiwdhid'

  namespace :admin do
      resources :dashboard, only: :index
    end

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  resources :ideas do
    resources :likes, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
  end
end

app/models/idea.rb
class Idea < ApplicationRecord
  has_many :likes, dependent: :destroy

  has_many :likers, through: :likes, source: :user

  # Like `belongs_to`, `has_many` tells Rails that Idea is associated to
  # the Review model.
  has_many :reviews, dependent: :destroy
  # `dependent: :destroy` will delete all associated reviews to the idea
  # before the idea is deleted.

  # `dependent: :nullify` will update the `idea_id` in all associated reviews
  # to `NULL` before the is deleted.

  # reviews
  # reviews<<(object, ...)
  # reviews.delete(object, ...)
  # reviews.destroy(object, ...)
  # reviews=(objects)
  # reviews_singular_ids
  # reviews_singular_ids=(ids)
  # reviews.clear
  # reviews.empty?
  # reviews.size
  # reviews.find(...)
  # reviews.where(...)
  # reviews.exists?(...)
  # reviews.build(attributes = {}, ...)
  # reviews.create(attributes = {})
  # reviews.create!(attributes = {})

  belongs_to :user

  # we can define validations here, validations will be called before saving
  # or before creating a record and will prevent the saving or creation from
  # happening if the validation rules are not met.
  # we can call `.save` we will get back `true` if it completes successfully and
  # will get back `false` if validations fail
  validates(:title, { presence: { message: 'must be provided' },
                      uniqueness: true
                    })
  validates(:description, { presence: true, length: { minimum: 5, maximum: 4000 }})

  validate :no_monkey

  after_save :capitalize_title

  def self.search(str)
    search_term = str
    where(["title ILIKE? OR description ILIKE?", "%#{search_term}%", "%#{search_term}%"]).order(:title, :description)
  end

  def self.recent(count)
    order({ created_at: :desc }).limit(count)
  end

  private

  def no_monkey
    if title.present? && title.downcase.include?('monkey')
      errors.add(:title, 'No monkey please! 🙈')
    end
  end

  def capitalize_title
    self.title = title.capitalize if title.present?
  end

  def destroy_notification
    Rails.logger.warn("The Idea #{self.title} is about to be deleted")
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  before_action :find_idea, only: [:edit, :destroy, :show, :update]

  before_action :authorize_user!, only: [:edit, :destroy, :update]

  def index
    @ideas = Idea.order(created_at: :desc)
  end

  def new
    @idea = Idea.new
    # render :new

  end

  def edit

  end

  def update
    if @idea.update idea_params
      redirect_to idea_path(@idea)
    else
      render :edit
    end
  end

  def destroy
    @idea.destroy
    redirect_to ideas_path
  end

  def show
    # @idea = Idea.find params[:id]
    @review = Review.new
    @like = @idea.likes.find_by(user: current_user)
    # Using association methods just builds queries, meaning that
    # we can continue chaining more and more query methods such order, limit, offset, where
    # , etc
    @reviews = @idea.reviews.order(created_at: :desc)
    # byebug
  end

  def create
    @idea = Idea.new idea_params
    @idea.user = current_user

    if @idea.save
      redirect_to idea_path(@idea)
    else
      # byebug
      # render :new
      referrer = request.referrer
      base_url = request.fullpath

      referrer.slice!(base_url)
      render referrer

    end
  end

  def modal_create
    @idea = Idea.new idea_params
    @idea.user = current_user

    if @idea.save
      redirect_to idea_path(@idea)
    else
      byebug
      render :new
    end
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description)
  end

  def find_idea
    @idea = Idea.find params[:id]
  end

  def authorize_user!
    unless can?(:manage, @idea)
      head :unauthorized
    end
  end

end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>

<% unless @idea.errors.empty? %>
<div>
  <%= @idea.errors.full_messages.join(', ') %>
</div>
<% end %>

<%= form_for @idea do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <%= f.submit %>
<% end %>

app/views/ideas/index.html.erb
<div style="padding-top:10px">
  <h1>All Ideas</h1>

  <% @ideas.each do |idea| %>
  <div class="ideas">
    <%= link_to idea.title, idea_path(idea) %>
    <br>
    <span class="idea-details"><strong>Title: <%=idea.title%></strong></span>
    <br>
    <div class="idea-description" style="display:none;"><%= idea.description %></div>
    <p><strong>By: </strong> <%= idea.user&.full_name %></p>
  </div>
  <hr />
  <% end %>
</div>

app/views/ideas/new-modal.html.erb
<h1>Create a New Idea via bs modal</h1>

app/views/ideas/new.html.erb
<h1>Create a New Idea</h1>
<%= render 'shared/form' %>

app/views/ideas/show.html.erb
<h1><%= @idea.title %></h1>
<br>
<p><%= @idea.description %></p>
<br>
<p><strong>Author: </strong> <%= @idea.user&.full_name %></p>
<br>

<div class="like-widget">
  <% if user_signed_in? && can?(:like, @idea) %>
    <% if @like.present? %>
      <%= link_to fa_icon('heart lg'), idea_like_path(@idea, @like), method: :delete %>
    <% else %>
      <%= link_to fa_icon('heart-o lg'), idea_likes_path(@idea), method: :post %>
    <% end %>
  <% end %>
  <%= pluralize @idea.likes.count, 'like' %>
</div>

<%# can? is a helper method that came from the CanCanCan gem which will check the
    rules in our /app/models/ability.rb file %>
<% if user_signed_in? && can?(:manage, @idea) %>
  <%= link_to 'Edit', edit_idea_path(@idea) %>
  <%= link_to 'Delete',
    idea_path(@idea),
    method: :delete %>
<% end %>

<div>
  <h3>Add a Review </h3>
  <% if user_signed_in? %>
    <%= errors_for @review %>

    <%= form_for [@idea, @review] do |f| %>
      <div>
        <%= f.label :body %>
        <%= f.text_area :body %>
      </div>
      <%= f.submit %>
    <% end %>
  <% end %>
</div>

<div class='review-list'>
  <% @reviews.each do |review| %>
    <div>
      <p>Body:<%= review.body %></p>
      <p><strong>By: </strong> <%= review.user&.full_name %></p>
      <p>
        <strong>Created at:</strong> <%= review.created_at.to_formatted_s(:long) %>
        <% if user_signed_in? && can?(:destroy, review) %>
            <span><%= link_to 'Delete', idea_review_path(@idea, review),
                method: :delete, data: { confirm: 'Are you sure?'} %></span>
        <% end %>
      </p>
    </div>
  <% end %>
</div>