config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  #
  # get 'sessions/create'
  #
  # get 'sessions/destroy'
  #
  # get 'users/new'
  #
  # get 'welcome/index'
  #
  # get 'welcome/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get('/', {to: 'welcome#index', as: 'home'})

  resources :stuff

  # get '/new_path/' => 'ideas#newhiwdhid'

  namespace :admin do
      resources :dashboard, only: :index
    end

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  resources :ideas do
    resources :likes, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>IdeaFactory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">

    <!-- TODO: add SEO meta tags -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">

    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> -->

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous"></script>

  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a href="#"><img src="https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/ca.svg" style="width:50px; padding:15px;" class="w3-hover-opacity"></a>

          <p class= "pull-bottom" style="color:white;">Idea Factory</p>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'New Idea', new_idea_path %></li>
            <li><%= link_to('All Ideas', ideas_path) %></li>
            <% if user_signed_in? %>
              <li style="color:white; padding:15px;">Hello, <%= current_user.full_name %>!</li>
              <li><%= link_to 'Sign Out', session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to('Sign In', new_session_path) %></li>
              <li><%= link_to('Sign Up', new_user_path) %></li>

            <% end %>
          </ul>
          <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal" data-whatever="@ainkaran">New Idea</button>
        </div>



      </div>
    </nav>


    <div>
      <% if flash[:notice] %>
        <div class='alert alert-success'>
          <%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class='alert alert-danger'>
          <%= flash[:alert] %></div>
      <% end %>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class='col-md-12' style="padding-top:100px;">


          <%= yield %>

        </div>
      </div>
    </div>

    <%= render 'shared/modal' %>

  </body>
</html>